FROM python:3.7-slim
WORKDIR /app
RUN pip3 install gunicorn

EXPOSE 5001

COPY ./search/ /app/
COPY requirements-dev.txt /app/requirements-dev.txt
COPY requirements-common.txt /app/requirements-common.txt
RUN pip3 install -e .

CMD ["gunicorn", "-w", "2", "--bind", ":5001", "search_service.search_wsgi"]